# Generated by Django 4.2.2 on 2023-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('content', models.CharField(max_length=130)),
                ('photo', models.ImageField(upload_to='works/')),
            ],
        ),
    ]
