# Generated by Django 4.2.2 on 2023-06-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='photo',
            field=models.ImageField(upload_to='works/media/'),
        ),
    ]
