# Generated by Django 4.2.2 on 2023-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_works_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='produce',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='works',
            name='photo',
            field=models.ImageField(upload_to='works/'),
        ),
    ]
