# Generated by Django 4.2.2 on 2023-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_works_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='making',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
