# Generated by Django 4.2.2 on 2023-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_works_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='condition',
            field=models.CharField(choices=[('continue', 'Continue'), ('contents', 'Contents')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
