# Generated by Django 4.2.2 on 2023-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_works_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='condition',
            field=models.CharField(choices=[('continue_ott', 'Continue_ott'), ('continue_movie', 'Continue_movie'), ('contents', 'Contents')], max_length=100),
        ),
    ]
