# Generated by Django 4.2.2 on 2023-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_works_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
